# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 0101 daily
    - cron: '1 1 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/63b332b00a20616d1b2f4747